name: Generate rule-sets
on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 8:00 AM UTC+8

jobs:
  generate_rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Download rulesets
        run: |
          curl -fSL --parallel --parallel-immediate \
            -o geolocation-!cn.json https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/sing/geo/geosite/geolocation-!cn.json \
            -o geoip-cn.txt https://raw.githubusercontent.com/DH-Teams/DH-Geo_AS_IP_CN/main/Geo_AS_IP_CN.txt \
            -o geoip-cn-ipv6.txt https://raw.githubusercontent.com/DH-Teams/DH-Geo_AS_IP_CN/main/Geo_AS_IP_CN_6.txt \
            -o netflix.json https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/sing/geo/geoip/netflix.json
          jq -Rn '[inputs | select(length > 0)]' geoip-cn.txt > geoip-cn.json
          jq -Rn '[inputs | select(length > 0)]' geoip-cn-ipv6.txt > geoip-cn-ipv6.json

      - name: Combine rulesets into second-last-rule.json
        run: |
          jq -n --slurpfile a geolocation-\!cn.json --slurpfile b geoip-cn.json --slurpfile c geoip-cn-ipv6.json '{
            version: 1,
            rules: [{
              type: "logical",
              mode: "and",
              rules: [
                {
                  domain: $a[0].rules[0].domain,
                  invert: true
                },
                {
                  ip_cidr: ($b[0] + $c[0])
                }
              ]
            }]
          }' > second-last-rule.json

      - name: Generate netflix-ipv6.json
        run: |
          jq '{
            version: .version,
            rules: [
              .rules[0] | {
                ip_cidr: [.ip_cidr[] | select(contains(":"))]
              }
            ]
          }' netflix.json > netflix-ipv6.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add second-last-rule.json netflix-ipv6.json
          git commit --allow-empty -m "Released on $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')"
          git push
